---
name: X11-Muralis
version: 0.10
author:
  - Kathryn Andersen
abstract: Perl module to display wallpaper on your desktop.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Basename: 0
  File::Find::Rule: 0
  File::Spec: 0
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  Image::Info: 0
  Module::Pluggable: 0
  Pod::Usage: 0
build_requires:
  Test::More: 0
provides:
  X11::Muralis:
    file: lib/X11/Muralis.pm
    version: 0.10
  X11::Muralis::Backend:
    file: lib/X11/Muralis/Backend.pm
    version: 0.10
  X11::Muralis::Backend::Feh:
    file: lib/X11/Muralis/Backend/Feh.pm
    version: 0.10
  X11::Muralis::Backend::Hsetroot:
    file: lib/X11/Muralis/Backend/Hsetroot.pm
    version: 0.10
  X11::Muralis::Backend::Qiv:
    file: lib/X11/Muralis/Backend/Qiv.pm
    version: 0.10
  X11::Muralis::Backend::Xloadimage:
    file: lib/X11/Muralis/Backend/Xloadimage.pm
    version: 0.10
  X11::Muralis::Backend::Xsri:
    file: lib/X11/Muralis/Backend/Xsri.pm
    version: 0.10
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
